In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("news.csv",index_col=None)
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [3]:
dataset=df.drop("Unnamed: 0",axis=1)
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
##Output since it is a supervised classification problem we are using label as output
y=dataset["label"]

In [5]:
x_train,x_test,y_train,y_test=train_test_split(dataset['text'],y,test_size=0.33,random_state=53)

In [6]:
##The input training data needs to be transformed into vector so that we can proceed with the model creation
hashvect=HashingVectorizer(stop_words='english',alternate_sign=False)
count_train=hashvect.fit_transform(x_train)
print(count_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119222 stored elements and shape (4244, 1048576)>
  Coords	Values
  (1, 26381)	0.1336306209562122
  (1, 46353)	0.1336306209562122
  (1, 76282)	0.1336306209562122
  (1, 124604)	0.1336306209562122
  (1, 271872)	0.2672612419124244
  (1, 354766)	0.1336306209562122
  (1, 355578)	0.1336306209562122
  (1, 380136)	0.2672612419124244
  (1, 399927)	0.1336306209562122
  (1, 413315)	0.2672612419124244
  (1, 421751)	0.2672612419124244
  (1, 452780)	0.1336306209562122
  (1, 506429)	0.5345224838248488
  (1, 612563)	0.1336306209562122
  (1, 615897)	0.1336306209562122
  (1, 626851)	0.1336306209562122
  (1, 639862)	0.1336306209562122
  (1, 691517)	0.1336306209562122
  (1, 740856)	0.1336306209562122
  (1, 777362)	0.2672612419124244
  (1, 798576)	0.1336306209562122
  (1, 907820)	0.2672612419124244
  (1, 1039472)	0.1336306209562122
  (2, 14361)	0.3333333333333333
  (2, 81229)	0.3333333333333333
  :	:
  (4243, 924171)	0.08478501284163323
  (4243, 934801)	0.028261670947211076
  (4243, 935153)	0.028261670947211076
  (4243, 935275)	0.028261670947211076
  (4243, 939307)	0.1130466837888443
  (4243, 946139)	0.028261670947211076
  (4243, 949760)	0.028261670947211076
  (4243, 953107)	0.028261670947211076
  (4243, 958756)	0.028261670947211076
  (4243, 958992)	0.028261670947211076
  (4243, 963256)	0.028261670947211076
  (4243, 963865)	0.028261670947211076
  (4243, 975215)	0.028261670947211076
  (4243, 982957)	0.14130835473605538
  (4243, 993015)	0.028261670947211076
  (4243, 1004174)	0.028261670947211076
  (4243, 1004879)	0.028261670947211076
  (4243, 1009763)	0.05652334189442215
  (4243, 1010115)	0.028261670947211076
  (4243, 1017691)	0.028261670947211076
  (4243, 1026684)	0.028261670947211076
  (4243, 1027460)	0.028261670947211076
  (4243, 1038430)	0.028261670947211076
  (4243, 1039483)	0.028261670947211076
  (4243, 1044795)	0.05652334189442215

In [7]:
count_test=hashvect.transform(x_test)

In [8]:
# hashvect.get_feature_names_out()
# to get the unique words from the dataset

In [9]:
# len(hashvect.get_feature_names_out())

In [10]:
## Moel Creation and finding the accuracy
classify=MultinomialNB()
classify.fit(count_train,y_train)
pred=classify.predict(count_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy:   %0.3f" % score)

cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

accuracy:   0.853

In [11]:
from sklearn.metrics import classification_report
report=classification_report(y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.79      0.97      0.87      1083

    accuracy                           0.85      2091
   macro avg       0.87      0.85      0.85      2091
weighted avg       0.87      0.85      0.85      2091

In [21]:
## Time to cross check if the news is correct or not

dataset["text"][11]

"Donald Trump’s organizational problems have gone from bad to worse to flat-out embarrassing. Here’s Politico with the play-by-play from this weekend’s Colorado GOP convention, the latest scene of Trump’s delegate-securing failure:\n\nUnlike in most other states, Republicans in Colorado scrapped plans for a more traditional primary or caucus to award its delegates to this summer’s national convention in Cleveland. Instead, the state GOP selected three delegates from each of the state’s seven congressional districts at individual contests in the days leading up to the state convention, and then the remaining 13 delegates at the statewide event this past weekend. It was a rather convoluted process that favored campaigns that understood the rules and that had the ground game necessary to take advantage of them—or, put another way, not the Trump campaign.\n\nAt the first two district-level contests, the billionaire’s team showed up without an approved list of delegates to pass out to attendees, leaving supporters unsure of whom to back. And then at last Thursday’s contest, two of the three delegates on the Trump campaign’s list weren’t actually on the official ballot since they failed to pay the necessary registration fees.\n\nThis past weekend’s mix-up, though, was an even bigger embarrassment since at least one of the seven misnumbered names on the Trump-sanctioned list lined up with a Cruz-supporting delegate, according to NBC News. (Even without that mix-up, though, Cruz would have likely swept the contest anyway given his well-oiled delegate-selecting machine.) The Trump camp, though, appeared to blame the state GOP for the mistake, pointing to discrepancies between the delegate guides posted on the party's website and the printed materials distributed at the event. “We'll do whatever it takes to protect the legitimacy of our support in Colorado,” Trump aide Alan Cobb told NBC, suggesting the campaign may challenge the results. “Clearly there are some serious issues with the ballot and balloting.”\n\nTrump remains the favorite to arrive at the convention with the most delegates to his name, but he’s far from assured of the majority of delegates he’d need to win the nomination on the first ballot. Given that reality, the GOP front-runner recently retooled his campaign to address his clear weaknesses in the under-the-radar battle to send loyal delegates to the convention. If those efforts don't start paying dividends soon, though, Trump very well may arrive in Cleveland with the most delegates—and leave without the nomination."

In [22]:
count_train[11]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 127 stored elements and shape (1, 1048576)>

In [15]:
hashvect = HashingVectorizer(stop_words='english')
count_train = hashvect.fit_transform(x_train)

In [23]:
x_train[[11]]

11    Donald Trump’s organizational problems have go...
Name: text, dtype: object

In [24]:
count_train[[11]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 127 stored elements and shape (1, 1048576)>

In [25]:
classify.predict(count_train[[10]])

array(['REAL'], dtype='<U4')